name: Pre-publish tasks

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean
      major-version:
        required: true
        type: number
      minor-version:
        required: true
        type: number
      patch-version:
        required: true
        type: number
    outputs:
      sha:
        description: Current SHA after version update
        value: ${{ jobs.pre-publish.outputs.sha }}

permissions:
  contents: write

jobs:
  pre-publish:
    name: Update version, tag repo, and return sha
    runs-on: self-hosted
    outputs:
      sha: ${{ steps.return-sha.outputs.sha }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Commit version to current branch
        id: commit-version
        if: ${{ inputs.release }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@aeron.io"
          echo ${{ inputs.major-version }}.${{ inputs.minor-version }}.${{ inputs.patch-version }} > version.txt
          git add version.txt
          git status
          git commit -m "${{ inputs.major-version }}.${{ inputs.minor-version }}.${{ inputs.patch-version }} version update."
          git push
      - name: Tag branch
        id: tag-branch
        if: ${{ inputs.release }}
        run: |
          git tag ${{ inputs.major-version }}.${{ inputs.minor-version }}.${{ inputs.patch-version }}
          git push origin refs/tags/${{ inputs.major-version }}.${{ inputs.minor-version }}.${{ inputs.patch-version }}
      - name: Return current SHA
        id: return-sha
        run: |
          git rev-parse HEAD
          echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"