name: Release

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail'

jobs:
#  ci:
#    uses: ./.github/workflows/ci.yml
#
#  ci-low-cadence:
#    uses: ./.github/workflows/ci-low-cadence.yml
#
#  codeql:
#    uses: ./.github/workflows/codeql.yml

  release:
    name: Release java artifacts
    permissions:
      contents: read
      packages: write
#    needs: [ ci, ci-low-cadence, codeql ]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release && inputs.release-version || github.sha }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV
      - name: Publish a release
        run: ./gradlew publish
        env:
          SIGNING_GPG_SECRET_KEY: ${{ secrets.signingKey }}
          SIGNING_GPG_PASSWORD: ${{ secrets.signingPassword }}
          OSSRH_USERNAME: ${{ secrets.ossrhUsername }}
          OSSRH_PASSWORD: ${{ secrets.ossrhPassword }}

  github-release:
    if: ${{ inputs.release }}
    name: Create Github Release after release
    permissions:
      contents: write
    needs: release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release-version }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.release-version }}
          release_name: Release ${{ inputs.release-version }}
          draft: true